// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBOfk7l7rz1yonFIv36hxJblY67JGVA0',
    appId: '1:536255364081:android:a4b16c43976a645f7ba250',
    messagingSenderId: '536255364081',
    projectId: 'glowfit-4dfe8',
    storageBucket: 'glowfit-4dfe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuNKUYtP0EkrOlMVbALpjtjhyHWVwVkQA',
    appId: '1:536255364081:ios:41e21d8eca95311b7ba250',
    messagingSenderId: '536255364081',
    projectId: 'glowfit-4dfe8',
    storageBucket: 'glowfit-4dfe8.firebasestorage.app',
    iosBundleId: 'com.rd.glowfit',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8aDfUef3jeGmbO8teUDP6abexIs_xJY',
    appId: '1:536255364081:web:f130279f6bb2b78f7ba250',
    messagingSenderId: '536255364081',
    projectId: 'glowfit-4dfe8',
    authDomain: 'glowfit-4dfe8.firebaseapp.com',
    storageBucket: 'glowfit-4dfe8.firebasestorage.app',
  );

}